name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Configure AWS Credential
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: build
        working-directory: ./frontend
        run: |
          npm ci
          npm run build
        env:
          VUE_APP_SAMPLE_ENV: ''

      - name: Copy files to S3
        working-directory: ./frontend
        run: |
          aws s3 sync dist/ s3://${{ secrets.AWS_S3_CONTENT_BUCKET }}