name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Deploy frontend application
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Configure AWS Credential
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: build
        working-directory: ./frontend
        run: |
          npm install -g yarn
          yarn
          yarn build
        env:
          VUE_APP_SAMPLE_ENV: ''

      - name: Copy files to S3
        working-directory: ./frontend
        run: |
          aws s3 sync build/ s3://${{ secrets.AWS_S3_CONTENT_BUCKET }}