name: Test

on: push

jobs:
  run-tests:
    name: Run Vue Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Run vue lint and test
        working-directory: ./frontend
        run: |
          npm ci
          npm run test:unit
          npm run test:unit