name: Lint

on: push

jobs:
  run-tests:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm ci

      - name: Run vue lint and test
        working-directory: ./frontend
        run: |
          npm run test:unit
          npm run test:unit